In [2]:
import pandas as pd
import re

df = pd.read_csv('metadata.csv')  # Or pd.read_json('metadata.json')
df = df.rename(columns={'param_name': 'parameter', 'default_value': 'input_value', 'input_type': 'param_type'})
df.head()

,url,method,parameter,param_type,input_value,form_action
0,http://localhost:8080/login.php,POST,username,text,NaN,login.php
1,http://localhost:8080/login.php,POST,password,password,NaN,login.php
2,http://localhost:8080/login.php,POST,Login,submit,Login,login.php
3,http://localhost:8080/login.php,POST,user_token,hidden,1da6e93560384bc52ca35601fc7e4ff4,login.php
4,http://localhost:8080/login.php,POST,username,text,NaN,login.php

In [6]:
# The apply lines here...
df['input_length'] = df['input_value'].apply(lambda x: len(str(x)))
df['num_special_chars'] = df['input_value'].apply(lambda x: len(re.findall(r'[^a-zA-Z0-9\s]', str(x))))
df['num_digits'] = df['input_value'].apply(lambda x: len(re.findall(r'\d', str(x))))
df['contains_sql_keyword'] = df['input_value'].apply(lambda x: bool(re.search(r'(select|union|drop|insert|delete|update)', str(x), re.IGNORECASE)))
df['contains_html_tag'] = df['input_value'].apply(lambda x: bool(re.search(r'<[^>]+>', str(x))))

columns = ['url', 'parameter', 'input_value', 'input_length', 'num_special_chars',
           'num_digits', 'param_type', 'contains_sql_keyword', 'contains_html_tag']
features_df = df[columns]
features_df.to_csv('features_extracted.csv', index=False)
features_df.head()

,url,parameter,input_value,input_length,num_special_chars,num_digits,param_type,contains_sql_keyword,contains_html_tag
0,http://localhost:8080/login.php,username,NaN,3,0,0,text,False,False
1,http://localhost:8080/login.php,password,NaN,3,0,0,password,False,False
2,http://localhost:8080/login.php,Login,Login,5,0,0,submit,False,False
3,http://localhost:8080/login.php,user_token,1da6e93560384bc52ca35601fc7e4ff4,32,0,20,hidden,False,False
4,http://localhost:8080/login.php,username,NaN,3,0,0,text,False,False